# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalAuth',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('passworld', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255, unique=True)),
                ('nickname', models.CharField(max_length=255)),
                ('register_datetime', models.DateTimeField(auto_now=True)),
                ('lasted_login', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='localauth',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='dashboard.User'),
        ),
    ]
