# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20160916_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localauth',
            old_name='passworld',
            new_name='password',
        ),
    ]
