# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20160916_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=2083)),
                ('host', models.CharField(max_length=68)),
                ('scheme', models.CharField(default='http', max_length=10)),
                ('content_length', models.IntegerField(default=0)),
                ('timestamp', models.IntegerField(default=0)),
                ('kinds', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='localauth',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
