# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20160928_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldata',
            name='host',
            field=models.CharField(error_messages={b'blank': 'host\u4e0d\u80fd\u80fd\u4e3a\u7a7a'}, max_length=68),
        ),
        migrations.AlterField(
            model_name='urldata',
            name='url',
            field=models.CharField(error_messages={b'blank': 'url\u4e0d\u80fd\u4e3a\u7a7a'}, max_length=2083),
        ),
    ]
