# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20161017_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='urldata',
            name='title',
            field=models.CharField(default=b'', max_length=2047),
        ),
        migrations.AddField(
            model_name='urldata',
            name='title_key',
            field=models.CharField(default=b'', max_length=2047),
        ),
    ]
