# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20161114_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='urldata',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
