# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_urldata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='titlecut',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
