# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_titlecut_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titlecut',
            name='category',
            field=models.CharField(blank=True, default=b"''", max_length=50),
        ),
        migrations.AlterField(
            model_name='titlecut',
            name='title_key',
            field=models.CharField(blank=True, default=b"''", max_length=2047),
        ),
    ]
