# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20161114_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titlecut',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='titlecut',
            name='title_key',
            field=models.CharField(blank=True, default=None, max_length=2047, null=True),
        ),
    ]
