# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-15 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20161114_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleClassificationLib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default=b'', max_length=2047)),
                ('category', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WordVocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=50)),
                ('freq', models.IntegerField(default=10)),
                ('pos', models.CharField(blank=True, default=b'', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='TitleCut',
        ),
        migrations.AddField(
            model_name='urldata',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='urldata',
            name='precision',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='urldata',
            name='record',
            field=models.IntegerField(default=0),
        ),
    ]
