# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-15 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20161115_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='titleclassificationlib',
            name='title_key',
            field=models.CharField(blank=True, default=None, max_length=2047, null=True),
        ),
    ]
