# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20161115_0724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urldata',
            old_name='precision',
            new_name='accuracy',
        ),
    ]
