# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-24 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20161124_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldata',
            name='timestamp',
            field=models.IntegerField(default=0.0, verbose_name='\u8bbf\u95ee\u65f6\u95f4'),
        ),
    ]
