# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-24 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20161124_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titleclassificationlib',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='titleclassificationlib',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
