# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-03 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20161124_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=50)),
            ],
        ),
    ]
