# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-03 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_categorytitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytitle',
            name='word',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='wordvocabulary',
            name='word',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
