# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-04 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_auto_20161203_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldata',
            name='category',
            field=models.CharField(blank=True, choices=[('IT', 'IT'), ('\u519b\u4e8b', '\u519b\u4e8b'), ('\u5a31\u4e50', '\u5a31\u4e50'), ('\u5b66\u672f', '\u5b66\u672f'), ('\u641c\u7d22', '\u641c\u7d22'), ('\u6e38\u620f', '\u6e38\u620f'), ('\u751f\u6d3b', '\u751f\u6d3b'), ('\u7f16\u7a0b', '\u7f16\u7a0b'), ('\u8d2d\u7269', '\u8d2d\u7269'), ('\u95f2\u901b', '\u95f2\u901b')], default=None, max_length=50, null=True, verbose_name='\u5206\u7c7b'),
        ),
        migrations.AlterField(
            model_name='urldata',
            name='title',
            field=models.CharField(blank=True, default=b'', max_length=2047, verbose_name='\u7f51\u5740\u6807\u9898'),
        ),
    ]
